---
  # ### ansible-playbook playbooks/ec2.yml --private-key=~/.ssh/vixletriakkey.pem##############
- name: Create a sandbox instance
  hosts: localhost
  gather_facts: true


  tasks:
    - name: Provision 1 EC2 instance
      ec2:
        key_name: vixletriakkey
        group: RiakDB # Security group
        instance_type: t2.micro
        image: ami-d05e75b8  # Ubuntu image
        wait: yes
        wait_timeout: 500
        region: us-east-1
        count: 2
        instance_tags:
          Name: dead2-stage-riak
          application: db-riak
          client: vixlet
          environment: staging
        volumes:
        - device_name: /dev/sda1
          snapshot: snap-4e3c6d2b
          volume_size: 10
        monitoring: yes
        vpc_subnet_id: subnet-bcb902cb
        assign_public_ip: yes
      register: ec2

    - name: Add new instance to host group
      add_host: hostname={{ item.public_ip }} groupname=riak_dead
      with_items: ec2.instances
    - name: Wait for SSH to come up
      wait_for: host={{ item.public_dns_name }} port=22 delay=60 timeout=320 state=started
      with_items: ec2.instances

- name: Configure instance(s)
  hosts: riak_dead
  remote_user: ubuntu
  sudo: True
  gather_facts: True

  tasks:
# Installs packages in Ubuntu system
    - name: install required packages
      apt: name={{ item }} update_cache=yes state=latest
      with_items:
          - git
          - ruby
#          - rubygems
          - bundler
